---
version: '2.1'
services:
  airdcpp:
    image: algonrey/airdcpp
    volumes:
      - airdcpp:/.airdcpp
    user: ${UID:-0}:${GID:-0}
    hostname: airdcpp
    ports:
      - ${HTTP_PORT:-5600}:5600
      - ${HTTPS_PORT:-5601}:5601
      - ${TCP_PORT:-21248}:${TCP_PORT:-21248}
      - ${UDP_PORT:-21248}:${UDP_PORT:-21248}/udp
      - ${TLS_PORT:-21249}:${TLS_PORT:-21249}

volumes:
  airdcpp:
    driver: local
